package com.horariolivre.entity;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Autorizacoes generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "autorizacao")
public class Autorizacao implements java.io.Serializable {

	private int id;
	private String nome;
	private String descricao;

	public Autorizacao() {
	}

	public Autorizacao(String nome) {
		this.nome = nome;
	}

	public Autorizacao(String nome, String descricao) {
		this.nome = nome;
		this.descricao = descricao;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 16)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao", length = 140)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
}
