package com.horariolivre.entity;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AutorizacoesUsuario generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "autorizacoes_usuario", uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class AutorizacoesUsuario implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Autorizacoes autorizacoes;

	public AutorizacoesUsuario() {
	}

	public AutorizacoesUsuario(Usuario usuario,			Autorizacoes autorizacoes) {
		this.usuario = usuario;
		this.autorizacoes = autorizacoes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_usuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_autorizacoes", nullable = false, insertable = false, updatable = false)
	public Autorizacoes getAutorizacoes() {
		return this.autorizacoes;
	}

	public void setAutorizacoes(Autorizacoes autorizacoes) {
		this.autorizacoes = autorizacoes;
	}

}
