package com.horariolivre.entity;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1

import java.sql.Time;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ConfigHorarioLivre generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "config_horario")
public class ConfigHorarioLivre implements java.io.Serializable {

	private int id;
	private Time horaInicial;
	private Time horaFinal;

	public ConfigHorarioLivre() {
		this.horaInicial = new Time(0);
		this.horaFinal = new Time(0);
	}
	
	public ConfigHorarioLivre(int id) {
		this.id = id;
	}

	public ConfigHorarioLivre(Time horaInicial, Time horaFinal) {
		this.horaInicial = horaInicial;
		this.horaFinal = horaFinal;
	}
	
	public ConfigHorarioLivre(int id, Time horaInicial, Time horaFinal) {
		this.id = id;
		this.horaInicial = horaInicial;
		this.horaFinal = horaFinal;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "hora_inicial")
	public Time getHoraInicial() {
		return this.horaInicial;
	}

	public void setHoraInicial(Time horaInicial) {
		this.horaInicial = horaInicial;
	}

	@Column(name = "hora_final")
	public Time getHoraFinal() {
		return this.horaFinal;
	}

	public void setHoraFinal(Time horaFinal) {
		this.horaFinal = horaFinal;
	}

}
