package com.horariolivre.entity;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DadosUsuario generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dados_usuario")
public class DadosUsuario implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Dados dados;
	private String conteudo;

	public DadosUsuario() {
	}

	public DadosUsuario(Usuario usuario, Dados dados, String conteudo) {
		this.usuario = usuario;
		this.dados = dados;
		this.conteudo = conteudo;
	}
	
	public DadosUsuario(int id_usuario, int id_dados, String conteudo) {
		this.usuario = new Usuario();
		this.usuario.setId(id_usuario);
		this.dados = new Dados(id_dados);
		this.conteudo = conteudo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_dados", nullable = false)
	public Dados getDados() {
		return this.dados;
	}

	public void setDados(Dados dados) {
		this.dados = dados;
	}

	@Column(name = "conteudo", length = 100)
	public String getConteudo() {
		return this.conteudo;
	}

	public void setConteudo(String conteudo) {
		this.conteudo = conteudo;
	}

}
