package com.horariolivre.entity;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HorarioLivre generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "horario_livre")
public class HorarioLivre implements java.io.Serializable {
	private int id;
	private Usuario usuario;
	private Evento evento;
	private Date data;
	private Date hora;
	private int duracao;

	public HorarioLivre() {
	}

	public HorarioLivre(Usuario usuario, Date data, Date hora, int duracao) {
		this.usuario = usuario;
		this.data = data;
		this.hora = hora;
		this.duracao = duracao;
	}
	
	public HorarioLivre(Evento evento, Date data, Date hora, int duracao) {
		this.evento = evento;
		this.data = data;
		this.hora = hora;
		this.duracao = duracao;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_evento", nullable = false)
	public Evento getEvento() {
		return evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 13)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", nullable = false, length = 15)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "duracao", nullable = false)
	public int getDuracao() {
		return this.duracao;
	}

	public void setDuracao(int duracao) {
		this.duracao = duracao;
	}
}
