package com.horariolivre.entity;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1


/**
 * Dados generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dados")
public class Key implements java.io.Serializable {

	private int id;
	private String nome;

	public Key() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
