package com.horariolivre.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1


/**
 * Dados generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "key")
public class Key implements java.io.Serializable {

	private int id;
	private String nome;

	public Key() {
	}
	
	public Key(String nome) {
		this.nome = nome;
	}

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
