package com.horariolivre.entity;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sessao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "sessao", uniqueConstraints = @UniqueConstraint(columnNames = "fk_usuario"))
public class Sessao implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private TipoSessao tipoSessao;

	public Sessao() {
	}

	public Sessao(Usuario usuario, TipoSessao tipoSessao) {
		this.usuario = usuario;
		this.tipoSessao = tipoSessao;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_usuario", unique = true)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo", nullable = false)
	public TipoSessao getTipoSessao() {
		return this.tipoSessao;
	}

	public void setTipoSessao(TipoSessao tipoSessao) {
		this.tipoSessao = tipoSessao;
	}

}
