package com.horariolivre.entity;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoSessao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tipo_sessao")
public class TipoSessao implements java.io.Serializable {

	private int id;
	private String titulo;

	public TipoSessao() {
	}

	public TipoSessao(String titulo) {
		this.titulo = titulo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "titulo", nullable = false, length = 20)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}
}
