package com.horariolivre.entity;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 24/03/2014 06:49:18 by Hibernate Tools 3.4.0.CR1

/**
 * Usuario generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	private int id;
	private String login;
	private String senha;
	private String primeiroNome;
	private String ultimoNome;

	public Usuario() {
	}

	public Usuario(String login, String senha) {
		this.setLogin(login);
		this.setSenha(senha);
	}

	public Usuario(String login, String senha, String primeiroNome, String ultimoNome) {
		this.setLogin(login);
		this.setSenha(senha);
		this.setPrimeiroNome(primeiroNome);
		this.setUltimoNome(ultimoNome);
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getPrimeiroNome() {
		return primeiroNome;
	}

	public void setPrimeiroNome(String primeiroNome) {
		this.primeiroNome = primeiroNome;
	}

	public String getUltimoNome() {
		return ultimoNome;
	}

	public void setUltimoNome(String ultimoNome) {
		this.ultimoNome = ultimoNome;
	}

}
